### ISSUE TITLE
Support local previews

### ISSUE THREAD

**Issue by smithjw1** [Automattic/vip-decoupled-bundle#70]
Currently previewing is only supported on the `home_url` of the current site.
https://github.com/Automattic/vip-decoupled-bundle/blob/trunk/preview/preview.php#L35

When a site is being used with the VIP Development Environment, the Node.js site often doesn't live at that URL. It lives at one more like http://localhost:9000.

Could we add a filter to allow a customer to pass in a static base URL for previews? That would allow for local development and applications where the home_url set in WordPress is not the same as the URL of the Node.js application.

**Comment by glassdoorwp** [comment]
Hi @smithjw1 is there any update on this issue?

**Comment by smithjw1** [comment]
Not at this time. We are planning to begin updates to the bundle next week. This will be considered for development at that time. You can expect an update in the next week or so.

**Comment by ingeniumed** [comment]
Hi @glassdoorwp, thanks for reporting this. I have reviewed this issue and I got some steps for you try that should solve the problem: 

1) Once you have spun up your VIP Development Environment for your site, and activated the plugin on the site go to Settings -> General in the local site's wp-admin.
2) In there, set the Site Address (URL) to the url for your frontend which is http://localhost:9000 (avoid prefixing the / at the end) and hit save.

After that, your preview links should work locally just as they do on your VIP site. I have attached a screenshot below for reference:

![Screenshot](https://github.com/Automattic/vip-decoupled-bundle/assets/1771524/5e1657b0-9d2a-46a2-9f79-f589a230151a)

We also have documentation on this [here](https://github.com/Automattic/vip-decoupled-bundle#setting-the-home-url) as well, that should be helpful. Let us know if this solves the problem 👍🏾

**Comment by ingeniumed** [comment]
I also want to note that, we have a Next.js skeleton template that is designed to work with this bundle plugin for your decoupled use cases. That can be found [here](https://github.com/Automattic/vip-go-nextjs-skeleton).

**Comment by glassdoorwp** [comment]
Hi @ingeniumed when I update the site address to localhost:9000 there are a couple issues:
1) Persistent error message from the `vip-decoupled` plugin:
<img width="875" alt="Screenshot 2023-10-26 at 11 55 40 AM" src="https://github.com/Automattic/vip-decoupled-bundle/assets/109179131/68934014-2225-46da-a8e1-7bed9c794ee5">

2) After saving this config and trying to edit a post, Gutenburg is trying to load assets from the wrong URL, thus the editor never loads.
<img width="691" alt="Screenshot 2023-10-26 at 11 55 33 AM" src="https://github.com/Automattic/vip-decoupled-bundle/assets/109179131/1c3f110e-1651-45ce-8faa-5fa0f4552908">

**Comment by ingeniumed** [comment]
Thanks for sending over that screenshot of the error that you see. It seems like you have a multisite setup, in which case the instructions that I provided would not apply. Apologies on that. The `home_url` and `site_url` should be the same on that settings page. 

Instead, what would need to happen is that `home_url` for the respective subsite would need to be changed. We have instructions for how you can do that [here](https://github.com/Automattic/vip-decoupled-bundle/blob/trunk/MULTISITE.md).

Let us know if this solves the problem 👍🏾

**Comment by smithjw1** [comment]
@glassdoorwp we've continued looking into this and uncovered a known issue in WordPress Core where if the ports (and perhaps protocols) don't match, things go wonky.

We are continuing our investigation, thanks for the additional information!

**Comment by alecgeatches** [comment]
@glassdoorwp Thank you for your feedback on this issue, and I apologize for the wait! We just merged https://github.com/Automattic/vip-decoupled-bundle/pull/81, which adds the ability to filter a preview URL to point to a custom location. Please let me know if this does not address your previewing issue.

---

Note that I tried creating a multisite locally and I was able to get previews working with a non-standard local port *without* using the filter above. In case you're able to solve this without the new filter, here were my settings:

![multisite-decoupled-options](https://github.com/Automattic/vip-decoupled-bundle/assets/17870752/24140b59-f91c-4acd-8f8f-e0ec8d8fabf8)

I did briefly see the same CORS errors [that you showed above](https://github.com/Automattic/vip-decoupled-bundle/issues/70#issuecomment-1781725860) in the editor, but those went away after I ensured the VIP Decoupled Bundle was installed and activated on the subsite.

The result was that I could preview just fine from a subsite domain to a non-standard local port:

https://github.com/Automattic/vip-decoupled-bundle/assets/17870752/52a6f116-f957-4c48-8fe0-fdb06eb7f2ca

---

Either way, hopefully configuration or the new `vip_decoupled_preview_url` filter can help solve preview redirection issues. Let us know if it doesn't!

**Comment by alecgeatches** [comment]
Going to close this issue as we've added a filtering ability in https://github.com/Automattic/vip-decoupled-bundle/pull/81, and there may be a way accomplish this setup through configuration alone.
