### ISSUE TITLE
Vulnerability Alert for WPGraphQL Plugin Version 1.17.0 in WPVIP Environment

### ISSUE THREAD

**Issue by jffry93** [Automattic/vip-decoupled-bundle#75]
I downloaded the vip-decoupled-bundle plugin and added it to the repo and vipbot is catching a vulnerability. I have attached a screenshot of the issue caught below. 

Bug Report
Bot Comment: wpcomvip-vipgoci-bot (VIP Code Analysis Bot) reported a vulnerability 33 minutes ago.

 
<img width="933" alt="Screenshot 2023-12-08 at 1 16 03 PM" src="https://github.com/Automattic/vip-decoupled-bundle/assets/59705751/2ab5cf6e-bd89-482d-a833-1a2e5e084e4b">

**Comment by smithjw1** [comment]
Thanks for reporting this! We'll look to get this updated ASAP. In the meantime, you can remove this version of WP GraphQL from the bundle and install WP GraphQL directly.

The other bundle functions will detect and use that installation.

**Comment by smithjw1** [comment]
I chatted with @alecgeatches about this, and he pointed out that the scanner is reporting the delta between our version and the most recent version. There isn't a vulnerability.

Scanning the [changelog](https://wordpress.org/plugins/wp-graphql/#developers), I see no reported security fixes in the 1.18 or 1.19.

We will work to update this to the latest version, but you can feel confident using the current version until we do so.
