### ISSUE TITLE
Request to Add Filter for Customizing Maximum Token Lifetime

### ISSUE THREAD

**Issue by artskidesign** [Automattic/vip-decoupled-bundle#78]
I have encountered a limitation regarding the maximum token lifetime, which is hard-coded to 3 hours ($max_lifetime = 3 * HOUR_IN_SECONDS;). This limitation is restrictive for my use case, where I require a longer token lifetime.

**Proposed Feature:**
I propose the addition of a filter in the get_token_lifetime_in_seconds function to allow users to modify the $max_lifetime value. This change would provide greater flexibility in managing token lifetimes according to different use cases.

**Suggested Implementation:**
The modification could be as simple as adding a filter hook in the function that determines the token lifetime. For example:

$max_lifetime = apply_filters( 'vip_decoupled_max_token_lifetime', 3 * HOUR_IN_SECONDS, $action, $post_id );

This change would allow developers to hook into this filter and set a custom maximum lifetime without directly modifying the plugin's core code.

**Benefits of the Change:**
Provides flexibility for different use cases that require longer or shorter token lifetimes.
Enhances the plugin's adaptability to various user requirements.
Maintains backward compatibility, as users who do not hook into this new filter will continue to use the default 3-hour limit.

**Additional Context:**
In my specific scenario, I need to extend the token lifetime to [describe your specific requirement, e.g., 1 year], which is currently not possible due to the hard-coded limit. This feature would significantly improve the plugin's utility in scenarios similar to mine.

Thank you for considering this feature request. I believe it would be a valuable addition to and would greatly appreciate any feedback or thoughts on this proposal.

**Comment by smithjw1** [comment]
This is an interesting request. Here's the relevant [line of code](https://github.com/Automattic/vip-decoupled-bundle/blob/93c6e4bac98c7b89fb5cf01461d09acf6ba94388/preview/token.php#L27).

Long-lived tokens have security implications, so we should hard-code an upper limit. But this does seem like an area where a filter can easily accommodate different use cases.

@artskidesign I couldn't tell if you were suggesting you would want to have tokens live up to one year. If so, could you say more about your use case?

**Comment by artskidesign** [comment]
Thank you for your feedback @smithjw1. I appreciate your concern regarding the security implications of long-lived tokens, and I agree that it's crucial to have a hard-coded upper limit for security reasons.

To address your question, yes, in my specific use case, I am considering the possibility of extending token lifetimes up to a longer period of time (yet to be decided what that would be). The primary reason for this is to accommodate a scenario where our application interacts with a set of users who engage with our platform infrequently, but when they do, they require extended access. This is particularly relevant in scenarios like reviews or infrequent, yet prolonged, auditing processes where users need uninterrupted access over extended periods.

Having a token that lasts up to a longer time would eliminate the need for these users to repeatedly renew their authentication, thereby enhancing their user experience while still maintaining a reasonable level of security. It's important to note that this extended lifetime would not be the default setting but an option for specific cases where such a need is justified.

I understand the risks associated with longer token lifetimes, such as increased exposure to token theft or misuse. To mitigate these risks, we plan to implement security measures, including:

Strict Access Control: Ensuring that only users with specific roles or permissions can be granted these long-lived tokens.
Auditing and Monitoring: Regularly monitoring token usage to quickly identify and respond to any suspicious activities.

By introducing the proposed filter, developers would have the flexibility to adjust the token lifetime according to their specific needs while adhering to a sensible upper limit.

I hope this clarifies my use case for extending the token lifetime. And thank you for looking into this.

**Comment by smithjw1** [comment]
By default, we expire tokens on a single use, but you can filter that. That filter explains the security concerns, so there is prior art here.

An enhancement would be displaying active tokens as part of the post or centrally in a new WP Admin screen. That would allow site owners to revoke tokens. 

Another enhancement would be a hook or filter in the validation step that would allow for customer-specific validation rules, such as checking to see if the user who issued the token had a specific role.

I know neither of these things are what @artskidesign is asking for, but I'm mentioning them in this context to see if others would find them helpful. If so I can create separate enhancement issues for each.

**Comment by artskidesign** [comment]
Thank you @smithjw1. Would you be able to confirm if adding the filter for $max_lifetime variable [here](https://github.com/Automattic/vip-decoupled-bundle/blob/93c6e4bac98c7b89fb5cf01461d09acf6ba94388/preview/token.php#L28C2-L28C11) is something you would be able to accommodate in the near future?

**Comment by smithjw1** [comment]
Yes! We work in cycles, so our next chance to pick up this work is the first full week of February. 

Of course, we are happy to review PRs if you want to get this into the world sooner.

**Comment by artskidesign** [comment]
Thank you @smithjw1. I prepared proposed change here: https://github.com/Automattic/vip-decoupled-bundle/pull/80
It's very small. Let me know if this is acceptable from your perspective or if you see anything that we should change.

Thanks again for looking into this!

**Comment by alecgeatches** [comment]
@artskidesign Thank you for your discussion and PR! Your changes in #80 have been merged and included in the `1.2.0` release: https://github.com/Automattic/vip-decoupled-bundle/releases/tag/1.2.0. Thank you!
